### ISSUE TITLE
Floating Header on Mobile

### ISSUE THREAD

**Issue by clintnetwork** [clintnetwork/stratis-guru-v2#5]
On mobile phone the floating menu (header) does not works, apparently the jQuery scroll event is not emit on mobile only)

![image](https://user-images.githubusercontent.com/5221349/50402193-e7fa3700-0794-11e9-82e9-0b8c2c1e493c.png)

@rigwild tu pourrai regarder l'origine de ce problème ?

Thanks

**Comment by rigwild** [comment]
Fixed this with #11 

It was `overflow-x: hidden;` that was blocking the event from being fired by jQuery.
